from django.urls import path
from . import views
from budgets.views import *
urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('assets-debts/', views.assets_debts, name='assets_debts'),
    path('assets-debts/add-asset', AddAsset.as_view(), name='add-asset'),
    path('assets-debts/add-installment-debt', AddInstallmentDebt.as_view(), name='add-installment-debt'),
    path('assets-debts/add-revolving-debt', AddRevolvingDebt.as_view(), name='add-revolving-debt'),
    path('assets-debts/assets/<int:id>/view/', views.view_asset_details),
    path('assets-debts/assets/<int:id>/update/', UpdateAsset.as_view()),
    path('assets-debts/assets/<int:id>/delete/', DeleteAsset.as_view()),
    path('assets-debts/assets/<int:id>/add-balance/', AddAssetBalance.as_view()),
    path('assets-debts/assets/<int:id>/update-balance/<int:bid>', UpdateAssetBalance.as_view()),
    path('assets-debts/assets/<int:id>/delete-balance/<int:bid>', DeleteAssetBalance.as_view()),
    path('assets-debts/installment-debts/<int:id>/view/', views.view_installment_debt_details),
    path('assets-debts/installment-debts/<int:id>/update/', UpdateInstallmentDebt.as_view()),
    path('assets-debts/installment-debts/<int:id>/delete/', DeleteInstallmentDebt.as_view()),
    path('assets-debts/installment-debts/<int:id>/add-balance/', AddInstallmentDebtBalance.as_view()),
    path('assets-debts/installment-debts/<int:id>/update-balance/<int:bid>', UpdateInstallmentDebtBalance.as_view()),
    path('assets-debts/installment-debts/<int:id>/delete-balance/<int:bid>', DeleteInstallmentDebtBalance.as_view()),
    path('assets-debts/revolving-debts/<int:id>/view/', views.view_revolving_debt_details),
    path('assets-debts/revolving-debts/<int:id>/update/', UpdateRevolvingDebt.as_view()),
    path('assets-debts/revolving-debts/<int:id>/delete/', DeleteRevolvingDebt.as_view()),
    path('assets-debts/revolving-debts/<int:id>/add-balance/', AddRevolvingDebtBalance.as_view()),
    path('assets-debts/revolving-debts/<int:id>/update-balance/<int:bid>', UpdateRevolvingDebtBalance.as_view()),
    path('assets-debts/revolving-debts/<int:id>/delete-balance/<int:bid>', DeleteRevolvingDebtBalance.as_view()),
    path('budget/', views.budget, name='budget'),
    path('budget/<month>/<int:year>/add-budget/', AddBudget.as_view()),
    path('budget/<month>/<int:year>/', views.specific_budget),
    path('budget/<month>/<int:year>/add-income-budget-item', AddIncomeBudgetItem.as_view(), name='add-income-budget-item'),
    path('budget/<month>/<int:year>/add-income-transaction', AddIncomeTransaction.as_view()),
    # path('budget/<month>/<int:year>/add-income-transaction', AddIncomeTransaction.as_view()),
    path('budget/<month>/<int:year>/add-expense-category', AddExpenseCategory.as_view()),
    path('budget/<month>/<int:year>/income-budget-item/<int:id>/view', views.view_income_budget_item),
    path('budget/<month>/<int:year>/next', views.change_budget),
    path('budget/<month>/<int:year>/previous', views.change_budget),
    path('budget/<month>/<int:year>/delete-budget/<int:id>', DeleteBudget.as_view()),


    # path('budget/<month>/<int:year>/add-budget', views.specific_budget),
    # path('budget/<month>/<int:year>/add-income', AddIncome.as_view(), name='add-income'),
    # path('schedule/', views.schedule, name='schedule'),
    # path('schedule/<month>/<int:year>', views.specific_schedule),
    # path('schedule/add-item/', views.schedule_add_item, name='schedule_add_item'),
    # path('schedule/edit-item/<int:id>/', views.schedule_edit_item, name='schedule_edit_item'),
    # path('reports/', views.reports, name='reports'),
    # path('transactions/', views.transactions, name='transactions'),
]

