# Generated by Django 3.0.8 on 2020-12-15 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('asset_type', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='InstallmentDebt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('initial_balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('date_opened', models.DateField(blank=True, null=True)),
                ('minimum_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('payoff_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RevolvingDebt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('initial_balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('date_opened', models.DateField(blank=True, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RevolvingDebtBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date', models.DateField(blank=True, null=True)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='budgets.RevolvingDebt')),
            ],
            options={
                'ordering': ('-date', 'debt'),
                'unique_together': {('debt', 'date')},
            },
        ),
        migrations.CreateModel(
            name='InstallmentDebtBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date', models.DateField(blank=True, null=True)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='budgets.InstallmentDebt')),
            ],
            options={
                'ordering': ('-date', 'debt'),
                'unique_together': {('debt', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AssetBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date', models.DateField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='budgets.Asset')),
            ],
            options={
                'ordering': ('-date', 'asset'),
                'unique_together': {('asset', 'date')},
            },
        ),
    ]
