# Generated by Django 4.2.3 on 2023-08-20 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("type", models.CharField(blank=True, max_length=50)),
                ("hidden", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="BudgetPeriod",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        choices=[
                            (1, "Jan"),
                            (2, "Feb"),
                            (3, "Mar"),
                            (4, "Apr"),
                            (5, "May"),
                            (6, "Jun"),
                            (7, "Jul"),
                            (8, "Aug"),
                            (9, "Sep"),
                            (10, "Oct"),
                            (11, "Nov"),
                            (12, "Dec"),
                        ],
                        default=8,
                    ),
                ),
                ("year", models.PositiveIntegerField(default=2023)),
                (
                    "starting_bank_balance",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=11, null=True
                    ),
                ),
                (
                    "starting_cash_balance",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=11, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Monthly budget info",
                "unique_together": {("user", "month", "year")},
            },
        ),
        migrations.CreateModel(
            name="ExpenseBudgetItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "planned_amount",
                    models.DecimalField(decimal_places=2, max_digits=11),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Expense", "Expense"),
                            ("Transfer", "Transfer"),
                            ("Reserve", "Reserve"),
                        ],
                        default="Expense",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IncomeBudgetItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "planned_amount",
                    models.DecimalField(decimal_places=2, max_digits=11),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Income", "Income"),
                            ("Transfer", "Transfer"),
                            ("Reserve", "Reserve"),
                        ],
                        default="Income",
                        max_length=50,
                    ),
                ),
                (
                    "budget_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="income_budget_items",
                        to="budgets.budgetperiod",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-planned_amount", "name"),
                "unique_together": {("user", "budget_period", "name")},
            },
        ),
        migrations.CreateModel(
            name="InstallmentDebt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("type", models.CharField(blank=True, max_length=50)),
                ("hidden", models.BooleanField(default=False)),
                (
                    "interest_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=11, null=True
                    ),
                ),
                (
                    "initial_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "minimum_payment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                ("payoff_date", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="RevolvingDebt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("type", models.CharField(blank=True, max_length=50)),
                ("hidden", models.BooleanField(default=False)),
                (
                    "interest_rate",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=11, null=True
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=11, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="ScheduleItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Income", "Income"),
                            ("Transfer", "Income Transfer"),
                            ("Reserve", "Income Reserve"),
                            ("Expense", "Expense"),
                            ("Transfer", "Expense Transfer"),
                            ("Reserve", "Expense Reserve"),
                        ],
                        default="Expense",
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=11)),
                ("first_due_date", models.DateField()),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("Weekly", "Weekly"),
                            ("Every two weeks", "Every two weeks"),
                            ("Monthly", "Monthly"),
                            ("Every two months", "Every two months"),
                            ("Quarterly", "Quarterly"),
                            ("Every six months", "Every six months"),
                            ("Yearly", "Yearly"),
                            ("One time only", "One time only"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IncomeTransaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=11)),
                ("cash", models.BooleanField(default=False)),
                ("date", models.DateField()),
                (
                    "budget_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="income_transactions",
                        to="budgets.incomebudgetitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-amount", "name"),
            },
        ),
        migrations.CreateModel(
            name="ExpenseTransaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=11)),
                ("credit_purchase", models.BooleanField(default=False)),
                ("credit_payoff", models.BooleanField(default=False)),
                ("cash", models.BooleanField(default=False)),
                ("date", models.DateField()),
                (
                    "expense_budget_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_transactions",
                        to="budgets.expensebudgetitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "budget_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_categories",
                        to="budgets.budgetperiod",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Expense categories",
                "unique_together": {("user", "name", "budget_period")},
            },
        ),
        migrations.AddField(
            model_name="expensebudgetitem",
            name="expense_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_budget_items",
                to="budgets.expensecategory",
            ),
        ),
        migrations.AddField(
            model_name="expensebudgetitem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="ContactEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason_for_contact", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("date_submitted", models.DateField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RevolvingDebtBalance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=11)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "debt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="budgets.revolvingdebt",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-date", "debt"),
                "unique_together": {("user", "debt", "date")},
            },
        ),
        migrations.CreateModel(
            name="InstallmentDebtBalance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=11)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "debt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="budgets.installmentdebt",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-date", "debt"),
                "unique_together": {("user", "debt", "date")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="expensebudgetitem",
            unique_together={("user", "name", "expense_category")},
        ),
        migrations.CreateModel(
            name="AssetBalance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=11)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="budgets.asset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-date", "asset"),
                "unique_together": {("user", "asset", "date")},
            },
        ),
    ]
