# Generated by Django 3.0.8 on 2021-01-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeBudgetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('month', models.CharField(choices=[('01', 'Jan'), ('02', 'Feb'), ('03', 'Mar'), ('04', 'Apr'), ('05', 'May'), ('06', 'Jun'), ('07', 'Jul'), ('08', 'Aug'), ('09', 'Sep'), ('10', 'Oct'), ('11', 'Nov'), ('12', 'Dec')], default='01', max_length=25)),
                ('year', models.IntegerField(default=2021)),
            ],
            options={
                'ordering': ('year', '-month', '-amount', 'name'),
                'unique_together': {('name', 'month', 'year')},
            },
        ),
    ]
