# Generated by Django 3.0.8 on 2021-01-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_incomebudgetitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBudgetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('year', models.PositiveIntegerField()),
                ('starting_revolving', models.DecimalField(decimal_places=2, max_digits=9)),
                ('starting_checking', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.DeleteModel(
            name='IncomeBudgetItem',
        ),
    ]
