# Generated by Django 3.0.8 on 2021-01-01 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_auto_20210101_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlybudgetinfo',
            options={'verbose_name_plural': 'Monthly budget info'},
        ),
    ]
