# Generated by Django 3.0.8 on 2021-01-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_auto_20210101_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybudgetinfo',
            name='month',
            field=models.IntegerField(choices=[(1, '01 - Jan'), (2, '02 - Feb')]),
        ),
        migrations.AlterField(
            model_name='monthlybudgetinfo',
            name='starting_checking',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybudgetinfo',
            name='starting_revolving',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybudgetinfo',
            name='year',
            field=models.PositiveIntegerField(default='2021'),
        ),
    ]
