# Generated by Django 3.0.8 on 2021-01-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_auto_20210101_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybudgetinfo',
            name='month',
            field=models.IntegerField(choices=[(1, '01 - Jan'), (2, '02 - Feb'), (3, '03 - Mar'), (4, '04 - Apr'), (5, '05 - May'), (6, '06 - Jun'), (7, '07 - Jul'), (8, '08 - Aug'), (9, '09 - Sep'), (10, '10 - Oct'), (11, '11 - Nov'), (12, '12 - Dec')], default=1),
        ),
    ]
