# Generated by Django 3.0.8 on 2021-01-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0006_auto_20210101_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybudgetinfo',
            name='year',
            field=models.PositiveIntegerField(default=2021),
        ),
    ]
