# Generated by Django 3.0.8 on 2021-01-02 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0007_auto_20210102_1530'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonthlyBudgetInfo',
            new_name='BudgetPeriod',
        ),
        migrations.CreateModel(
            name='IncomeTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('budget_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itransactions', to='budgets.BudgetPeriod')),
            ],
            options={
                'ordering': ('-amount', 'name'),
                'unique_together': {('budget_period', 'name')},
            },
        ),
    ]
