# Generated by Django 3.0.8 on 2021-01-02 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0009_auto_20210102_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date', models.DateField()),
                ('budget_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_transactions', to='budgets.IncomeBudgetItem')),
            ],
            options={
                'ordering': ('-amount', 'name'),
                'unique_together': {('budget_item', 'name')},
            },
        ),
    ]
