# Generated by Django 3.0.8 on 2021-01-04 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0010_incometransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('budget_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='budgets.BudgetPeriod')),
            ],
            options={
                'verbose_name_plural': 'Expense categories',
                'unique_together': {('name',)},
            },
        ),
    ]
