# Generated by Django 3.0.8 on 2021-01-04 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0011_expensecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseBudgetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_budget_items', to='budgets.ExpenseCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_transactions', to='budgets.ExpenseBudgetItem')),
            ],
        ),
    ]
