# Generated by Django 3.0.8 on 2021-01-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0012_expensebudgetitem_expensetransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensetransaction',
            old_name='expense_category',
            new_name='expense_budget_item',
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='date',
            field=models.DateField(default='2021-01-03'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='expensebudgetitem',
            unique_together={('name', 'expense_category')},
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('name', 'budget_period')},
        ),
    ]
