# Generated by Django 3.0.8 on 2021-01-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0013_auto_20210103_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetransaction',
            name='credit_purchase',
            field=models.BooleanField(default=False),
        ),
    ]
