# Generated by Django 3.0.8 on 2021-01-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0014_expensetransaction_credit_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentdebt',
            name='type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='revolvingdebt',
            name='type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
