# Generated by Django 3.0.8 on 2021-01-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0015_auto_20210123_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentdebt',
            name='minimum_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
