# Generated by Django 3.0.8 on 2021-01-25 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0016_auto_20210123_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetperiod',
            name='month',
            field=models.IntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], default=1),
        ),
        migrations.AlterField(
            model_name='incometransaction',
            name='budget_item',
            field=models.ForeignKey(limit_choices_to={'budget_period_id': 11}, on_delete=django.db.models.deletion.CASCADE, related_name='income_transactions', to='budgets.IncomeBudgetItem'),
        ),
    ]
