# Generated by Django 3.0.8 on 2021-03-10 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0017_auto_20210125_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetransaction',
            name='credit_payoff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='budgetperiod',
            name='month',
            field=models.IntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], default=3),
        ),
        migrations.AlterField(
            model_name='incometransaction',
            name='budget_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_transactions', to='budgets.IncomeBudgetItem'),
        ),
    ]
