# Generated by Django 3.0.8 on 2021-03-10 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0018_auto_20210309_2150'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expensebudgetitem',
            unique_together=set(),
        ),
    ]
