# Generated by Django 3.0.8 on 2021-03-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0019_auto_20210309_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensebudgetitem',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='expensebudgetitem',
            unique_together={('name', 'expense_category')},
        ),
    ]
