# Generated by Django 3.0.8 on 2021-03-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0020_auto_20210309_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetperiod',
            name='starting_checking',
        ),
        migrations.RemoveField(
            model_name='budgetperiod',
            name='starting_revolving',
        ),
        migrations.AddField(
            model_name='expensebudgetitem',
            name='credit_debt',
            field=models.BooleanField(default=False),
        ),
    ]
