# Generated by Django 3.0.8 on 2021-03-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0021_auto_20210311_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('first_due_date', models.DateField()),
                ('frequency', models.CharField(choices=[('One time only', 'One time only'), ('Weekly', 'Weekly'), ('Every two weeks', 'Every two weeks'), ('Monthly', 'Monthly'), ('Every two months', 'Every two months'), ('Quarterly', 'Quarterly'), ('Every six months', 'Every six months'), ('Yearly', 'Yearly')], max_length=50)),
            ],
        ),
    ]
