# Generated by Django 3.0.8 on 2021-03-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0022_scheduleitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
