# Generated by Django 3.0.8 on 2021-03-29 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0025_auto_20210328_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmentdebt',
            name='initial_balance',
        ),
        migrations.RemoveField(
            model_name='revolvingdebt',
            name='initial_balance',
        ),
    ]
