# Generated by Django 3.0.8 on 2021-03-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0026_auto_20210329_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentdebt',
            name='initial_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
