# Generated by Django 3.0.8 on 2021-03-29 07:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgets', '0027_installmentdebt_initial_amount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='installmentdebt',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='revolvingdebt',
            unique_together={('user', 'name')},
        ),
    ]
