# Generated by Django 3.0.8 on 2021-03-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0028_auto_20210329_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentdebt',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='revolvingdebt',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
