# Generated by Django 3.0.8 on 2021-03-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0029_auto_20210329_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
