# Generated by Django 3.0.8 on 2021-03-30 22:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgets', '0030_auto_20210329_0207'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assetbalance',
            unique_together={('user', 'asset', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='installmentdebtbalance',
            unique_together={('user', 'debt', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='revolvingdebtbalance',
            unique_together={('user', 'debt', 'date')},
        ),
    ]
