# Generated by Django 3.0.8 on 2021-03-30 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0031_auto_20210330_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset_type',
            new_name='type',
        ),
    ]
