# Generated by Django 3.0.8 on 2021-03-30 23:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgets', '0032_auto_20210330_1741'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budgetperiod',
            unique_together={('user', 'month', 'year')},
        ),
    ]
