# Generated by Django 3.0.8 on 2021-03-31 01:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgets', '0033_auto_20210330_1858'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expensebudgetitem',
            unique_together={('user', 'name', 'expense_category')},
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('user', 'name', 'budget_period')},
        ),
        migrations.AlterUniqueTogether(
            name='incomebudgetitem',
            unique_together={('user', 'budget_period', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='incometransaction',
            unique_together={('user', 'budget_item', 'name')},
        ),
    ]
