# Generated by Django 3.0.8 on 2021-03-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0034_auto_20210330_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='frequency',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Every two weeks', 'Every two weeks'), ('Monthly', 'Monthly'), ('Every two months', 'Every two months'), ('Quarterly', 'Quarterly'), ('Every six months', 'Every six months'), ('Yearly', 'Yearly'), ('One time only', 'One time only')], max_length=50),
        ),
    ]
