# Generated by Django 3.0.8 on 2021-03-31 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0035_auto_20210331_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleitem',
            name='category',
        ),
    ]
