# Generated by Django 3.0.8 on 2021-03-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0036_remove_scheduleitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
