# Generated by Django 3.0.8 on 2021-04-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0038_auto_20210420_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetperiod',
            name='add_money_schedule_items',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budgetperiod',
            name='use_last_budget',
            field=models.BooleanField(default=False),
        ),
    ]
