# Generated by Django 3.0.8 on 2021-05-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0039_auto_20210425_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensebudgetitem',
            name='credit_debt',
        ),
        migrations.AddField(
            model_name='expensebudgetitem',
            name='transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incomebudgetitem',
            name='transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='budgetperiod',
            name='month',
            field=models.IntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], default=5),
        ),
    ]
