# Generated by Django 3.0.8 on 2021-05-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0040_auto_20210510_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomebudgetitem',
            name='transfer',
            field=models.BooleanField(default=False, help_text='Test'),
        ),
    ]
