# Generated by Django 3.0.8 on 2021-05-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0041_auto_20210510_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomebudgetitem',
            name='transfer',
            field=models.BooleanField(default=False),
        ),
    ]
