# Generated by Django 3.0.8 on 2021-05-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0042_auto_20210510_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetperiod',
            name='planned_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
