# Generated by Django 3.0.8 on 2021-05-11 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0043_budgetperiod_planned_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetperiod',
            old_name='planned_amount',
            new_name='starting_bank_balance',
        ),
    ]
