# Generated by Django 3.0.8 on 2021-05-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0044_auto_20210510_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetperiod',
            name='starting_bank_balance',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
