# Generated by Django 3.0.8 on 2021-05-16 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0045_auto_20210510_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetperiod',
            name='use_last_budget',
        ),
        migrations.AddField(
            model_name='budgetperiod',
            name='template_budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.BudgetPeriod'),
        ),
    ]
