# Generated by Django 3.0.8 on 2021-05-16 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0046_auto_20210516_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetperiod',
            name='template_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.BudgetPeriod'),
        ),
    ]
