# Generated by Django 3.0.8 on 2021-05-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0047_auto_20210516_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installmentdebt',
            name='date_opened',
        ),
        migrations.RemoveField(
            model_name='revolvingdebt',
            name='date_opened',
        ),
        migrations.AddField(
            model_name='expensebudgetitem',
            name='type',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Transfer Funds', 'Transfer Funds'), ('Reserve Funds', 'Reserve Funds')], default='Expense', max_length=50),
        ),
    ]
