# Generated by Django 3.0.8 on 2021-05-18 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0048_auto_20210517_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensebudgetitem',
            name='transfer',
        ),
    ]
