# Generated by Django 3.0.8 on 2021-05-19 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0049_remove_expensebudgetitem_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetperiod',
            name='add_money_schedule_items',
        ),
        migrations.RemoveField(
            model_name='budgetperiod',
            name='template_budget',
        ),
    ]
