# Generated by Django 3.0.8 on 2021-06-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0050_auto_20210518_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomebudgetitem',
            name='transfer',
        ),
        migrations.AddField(
            model_name='incomebudgetitem',
            name='type',
            field=models.CharField(choices=[('Income', 'Income'), ('Transfer', 'Transfer'), ('Reserve', 'Reserve')], default='Income', max_length=50),
        ),
        migrations.AlterField(
            model_name='budgetperiod',
            name='month',
            field=models.IntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], default=6),
        ),
        migrations.AlterField(
            model_name='expensebudgetitem',
            name='type',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Transfer', 'Transfer'), ('Reserve', 'Reserve')], default='Expense', max_length=50),
        ),
    ]
