# Generated by Django 3.0.8 on 2021-06-02 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0051_auto_20210601_2337'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='incometransaction',
            unique_together=set(),
        ),
    ]
