# Generated by Django 3.0.8 on 2021-07-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0052_auto_20210602_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetperiod',
            name='month',
            field=models.IntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], default=7),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
