# Generated by Django 3.0.8 on 2021-09-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0055_auto_20210925_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='budgetperiod',
            name='starting_bank_balance',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='expensebudgetitem',
            name='planned_amount',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='expensetransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='incomebudgetitem',
            name='planned_amount',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='incometransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='installmentdebt',
            name='initial_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='installmentdebt',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='installmentdebt',
            name='minimum_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='installmentdebtbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='revolvingdebt',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='revolvingdebt',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='revolvingdebtbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
