# Generated by Django 3.0.8 on 2021-09-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0056_auto_20210925_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installmentdebt',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='revolvingdebt',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
