# Generated by Django 3.0.8 on 2022-01-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0058_auto_20220117_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetperiod',
            name='starting_cash_balance',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
    ]
