# Generated by Django 3.0.8 on 2022-01-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0059_budgetperiod_starting_cash_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetransaction',
            name='cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incometransaction',
            name='cash',
            field=models.BooleanField(default=False),
        ),
    ]
