# Generated by Django 3.0.8 on 2022-01-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0060_auto_20220125_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetperiod',
            name='starting_bank_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='budgetperiod',
            name='starting_cash_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11, null=True),
        ),
    ]
