# Generated by Django 3.0.8 on 2022-04-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0061_auto_20220125_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='type',
            field=models.CharField(choices=[('Expense', 'Income Expense'), ('Transfer', 'Income Transfer'), ('Reserve', 'Income Reserve'), ('Expense', 'Expense Expense'), ('Transfer', 'Expense Transfer'), ('Reserve', 'Expense Reserve')], default='Expense', max_length=50),
        ),
        migrations.AlterField(
            model_name='budgetperiod',
            name='month',
            field=models.IntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], default=4),
        ),
    ]
