# Generated by Django 3.0.8 on 2022-04-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0062_auto_20220404_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='type',
            field=models.CharField(choices=[('Income', 'Income'), ('Transfer', 'Income Transfer'), ('Reserve', 'Income Reserve'), ('Expense', 'Expense'), ('Transfer', 'Expense Transfer'), ('Reserve', 'Expense Reserve')], default='Expense', max_length=50),
        ),
    ]
