# Generated by Django 3.0.8 on 2023-01-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0065_auto_20220912_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetperiod',
            name='month',
            field=models.IntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')], default=1),
        ),
        migrations.AlterField(
            model_name='budgetperiod',
            name='year',
            field=models.PositiveIntegerField(default=2023),
        ),
    ]
