# Generated by Django 4.2.3 on 2023-07-30 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0068_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
