# Generated by Django 4.2.3 on 2023-08-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0071_alter_budgetperiod_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installmentdebt',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revolvingdebt',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
